
--vendabem.com.br
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('1', 'Cine Marquise Ultravisão', 'R. Rio Grande do Sul, 1007 - Centro, Poços de Caldas - MG, 37701-001', NULL, 'https://cinemarquise.vendabem.com/compra_ingresso_online_new/?filial=001', 'https://www.cinemarquise.com.br/ultravisao/programacao', '2025-07-09 19:00:02.360304');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('2', 'Santa Maria - Brasília/DF', 'Santa Maria Shopping, Av. Alagado Cl 114, s/n - Santa Maria, Brasília - DF, 72544-204', NULL, 'https://www.multicinecinemas.com.br/brasilia/programacao', 'https://www.multicinecinemas.com.br/brasilia/programacao', '2025-07-10 13:03:49.888217');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('3', 'Cidade Jardim Goiânia/GO', 'Localizado em: Shopping Cidade Jardim. Endereço: Av. Nero Macedo, 400 - Cidade Jardim, Goiânia - GO, 74423-250', NULL, 'https://www.multicinecinemas.com.br/goiania/programacao', 'https://www.multicinecinemas.com.br/goiania/programacao', '2025-07-10 12:59:38.326086');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('4', 'Mossoró/RN', 'Partage Shopping Mossoró, Av. João da Escóssia, 1515 - Nova Betânia, Mossoró - RN, 59607-330', NULL, 'https://www.multicinecinemas.com.br/mossoro/programacao', 'https://www.multicinecinemas.com.br/mossoro/programacao', '2025-07-10 13:01:54.990014');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('5', 'Águas Lindas/GO', 'Avenida SANTA LUZIA, QD 00, LT. 6-B-2 Mansões Centro- oeste, Águas Lindas de Goiás - GO, 72915-705', NULL, 'https://www.multicinecinemas.com.br/aguas-lindas/programacao', 'https://www.multicinecinemas.com.br/aguas-lindas/programacao', '2025-07-10 12:57:24.871767');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('6', 'Iandê Shopping Caucaia/CE', ' Iandê Shopping Caucaia 620 - Av. Edson da Mota Correa - Centro, Caucaia - CE, 61600-050', NULL, 'https://www.multicinecinemas.com.br/caucaia/programacao', 'https://www.multicinecinemas.com.br/caucaia/programacao', '2025-07-10 13:00:34.526264');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('7', 'Cine Marquise Paulista', 'Av. Paulista, 2073 - Cerqueira César, São Paulo - SP, 01311-940', NULL, 'https://cinemarquise.vendabem.com/compra_ingresso_online_new/?filial=002', 'https://www.cinemarquise.com.br/paulista/programacao', '2025-07-09 19:00:02.360304');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('8', 'Jataí/GO', 'Localizado em: Jatahy Shopping. Endereço: Av. Pres. Tancredo Neves, 100 - Loja 35 - St. Epaminondas II, Jataí - GO, 75805-123', NULL, 'https://www.multicinecinemas.com.br/jatai/programacao', 'https://www.multicinecinemas.com.br/jatai/programacao', '2025-07-10 13:01:19.024318');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('9', 'Parnaíba/PI', 'Localizado em Paraíba Shopping. Av. São Sebastião, 3429 - Reis Veloso, Parnaíba - PI, 64204-035', NULL, 'https://www.multicinecinemas.com.br/parnaiba/programacao', 'https://www.multicinecinemas.com.br/parnaiba/programacao', '2025-07-10 13:02:40.168531');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('12', 'Brasil Center Shopping Valparaíso/GO', 'Brasil Center Shopping - Av. Marginal - Parque Esplanada III, Valparaíso de Goiás - GO, 72876-359', NULL, 'https://www.multicinecinemas.com.br/valparaiso/programacao', 'https://www.multicinecinemas.com.br/valparaiso/programacao', '2025-07-10 12:58:33.275949');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('13', 'Sobral/CE', 'Localizado em: Sobral Shopping. Endereço: Av. Monsenhor José Aloísio Pinto, 300 - Dom Expedito, Sobral - CE, 62050-255', NULL, 'https://www.multicinecinemas.com.br/sobral/programacao', 'https://www.multicinecinemas.com.br/sobral/programacao', '2025-07-10 13:04:57.843183');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('14', 'Shopping Itaguaçu - São José/SC', 'Localizado em: Shopping Itaguaçu. Endereço: R. Gerôncio Thives, 1079 - Barreiros, São José - SC, 88117-900', NULL, 'https://www.multicinecinemas.com.br/sao-jose/programacao', 'https://www.multicinecinemas.com.br/sao-jose/programacao', '2025-07-10 13:04:25.163331');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('16', 'Pb Shopping - Pato Branco/PR', 'Localizado em: PB Shopping. Endereço: R. Abel Bortot, 1450 - São Luiz, Pato Branco - PR, 85504-280', NULL, 'https://www.multicinecinemas.com.br/pato-branco/programacao', 'https://www.multicinecinemas.com.br/pato-branco/programacao', '2025-07-10 13:03:14.750207');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('35', 'Itajaí Shopping - SC', 'Itajaí Shopping - R. Samuel Heusi, 234 - Centro, Itajaí - SC, 88301-320', NULL, 'https://arcoplex.vendabem.com/compra_ingresso_online_new/?filial=005', 'https://www.arcoplex.com.br/itajai_shopping/programacao', '2025-11-30 14:27:49.423823');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('37', 'Cachorrinha - RS - Shopping do Vale', 'Shopping do Vale: Av. Gen. Flores da Cunha, 4001 - Vila Bom Principio, Cachoeirinha - RS, 94950-001', NULL, 'https://arcoplex.vendabem.com/compra_ingresso_online_new/?filial=013', 'https://www.arcoplex.com.br/shopping_do_vale/programacao', '2025-11-30 14:30:15.149611');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('47', 'Partage Jaraguá do Sul - SC', 'Av. Getúlio Vargas, 268 - Centro, Jaraguá do Sul - SC, 89251-970', NULL, 'https://arcoplex.vendabem.com/compra_ingresso_online_new/?filial=047', 'https://www.arcoplex.com.br/jaragua_do_sul/programacao', '2025-11-30 14:35:28.289908');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('36', 'Pátio Limeira - SP', 'Pátio Limeira Shopping: R. Carlos Gomes, 1321 - 2º andar - Centro, Limeira - SP, 13480-013', NULL, 'https://arcoplex.vendabem.com/compra_ingresso_online_new/?filial=036', 'https://www.arcoplex.com.br/patio_limeira/programacao', '2025-11-30 14:32:26.449052');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('46', 'Águas Claras Shopping - DF', 'Águas Claras Shopping: Av. das Araucárias, 1835/2005 - Águas Claras, Brasília - DF, 71936-250', NULL, NULL, NULL, '2025-11-30 14:33:45.212717');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('38', 'Lajeado Shopping - RS', 'Lajeado Shopping: BR-386, KM 346 - São Cristóvão, Lajeado - RS, 95900-000', NULL, 'https://arcoplex.vendabem.com/compra_ingresso_online_new/?filial=032', 'https://www.arcoplex.com.br/lajeado/programacao', '2025-11-30 14:31:24.731147');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('51', 'Passo Fundo - RS - Bella Città Shopping Center', 'Bella Città - R. Coronel Chicuta, 355 - Centro, Passo Fundo - RS, 99025-400', NULL, 'https://arcoplex.vendabem.com/compra_ingresso_online_new/?filial=051', 'https://www.arcoplex.com.br/bella_citta/programacao', '2025-11-30 14:37:30.502602');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('54', 'Santa Maria - RS - Royal Plaza Shopping', 'Av. Nossa Sra. das Dores, 305 - Nossa Sra. das Dores, Santa Maria - RS, 97050-531', NULL, 'https://arcoplex.vendabem.com/compra_ingresso_online_new/?filial=054', 'https://www.arcoplex.com.br/royal_plaza/programacao', '2025-11-30 14:38:40.094653');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('55', 'Palhoça - SC - Shopping ViaCatarina', 'Av. Atílio Pedro Pagani, 270 - Caminho Novo, Palhoça - SC, 88132-149', NULL, 'https://arcoplex.vendabem.com/compra_ingresso_online_new/?filial=055', 'https://www.arcoplex.com.br/via_catarina/programacao', '2025-11-30 14:39:39.481638');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('59', 'Blumenau - SC - Shopping Park Europeu', 'Rodovia Paul Fritz Kuehnrich, 1600 - Itoupava Norte, Blumenau - SC, 89052-381', NULL, 'https://arcoplex.vendabem.com/compra_ingresso_online_new/?filial=059', 'https://www.arcoplex.com.br/park_europeu/programacao', '2025-11-30 14:40:40.129176');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('60', 'Center Shopping Araranguá - SC', 'Av. Sete de Setembro, 705 - Cidade Alta, Araranguá - SC, 88901-004', NULL, 'https://arcoplex.vendabem.com/compra_ingresso_online_new/?filial=060', 'https://www.arcoplex.com.br/ararangua/programacao', '2025-11-30 14:41:38.65');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('61', 'Arcoplex Shopping Gravataí - RS', 'Estacionamento - Av. Centenário, 555 - Loja 159 - Passo das Pedras, Gravataí - RS, 94035-240', NULL, 'https://arcoplex.vendabem.com/compra_ingresso_online_new/?filial=061', 'https://www.arcoplex.com.br/gravatai/programacao', '2025-11-30 14:43:04.238385');
--ingresso.com
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('17', 'Cine Cambuí', 'Ed. Tatita - Praça Cel. Justiniano, 72 - Centro, Cambuí - MG, 37600-000', NULL, 'https://www.ingresso.com/?city=cambui&partnership=home', 'https://www.ingresso.com/?city=cambui&partnership=home', '2025-07-15 16:03:30.404702');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('18', 'GNC Balneário Shopping', 'Av Santa Catarina, 1, 6 - Bairro dos Estados, Balneário Camboriu', NULL, 'https://www.ingresso.com/cinema/gnc-balneario-shopping?city=balneario-camboriu', 'https://www.gnccinemas.com.br', '2025-10-13 15:02:22.788453');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('19', 'GNC Caxias do Sul', 'RST 453, 2780 LOJA 218 - Distrito Industrial- Caxias do Sul, Caxias do Sul', NULL, 'https://www.ingresso.com/cinema/gnc-caxias?city=caxias-do-sul', 'https://www.gnccinemas.com.br', '2025-10-13 15:03:20.368673');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('20', 'GNC Moinhos Porto Alegre', 'R. Olavo Barreto Viana, 36 LOJA C-01- Moinhos de Vento, Porto Alegre', NULL, 'https://www.ingresso.com/cinema/gnc-cinemas-moinhos?city=porto-alegre', 'https://www.gnccinemas.com.br', '2025-10-13 15:07:35.889668');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('21', 'GNC Iguatemi Porto Alegre', 'Av. João Walling , 1800 Loja 273 Piso JW - Chácara das Pedras, Porto Alegre', NULL, 'https://www.ingresso.com/cinema/gnc-iguatemi-porto-alegre?city=porto-alegre', 'https://www.gnccinemas.com.br', '2025-10-13 15:08:06.232467');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('22', 'GNC Praia de Belas', 'R. Praia de Belas, 1181 LOJA 0123- Praia de Belas, Porto Alegre', NULL, 'https://www.ingresso.com/cinema/gnc-praia-de-belas?city=porto-alegre', 'https://www.gnccinemas.com.br', '2025-10-13 15:08:36.643434');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('23', 'GNC Garten Shopping Joinville', 'Av. Rolf West, 333 ANCORA 06- Bom Retiro, Joinville', NULL, 'https://www.ingresso.com/cinema/gnc-garten-shopping?city=joinville', 'https://www.gnccinemas.com.br', '2025-10-13 15:10:23.967937');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('24', 'GNC Joinville Mueller', 'R. Visconde de Taunay, 235 LOJAS C1, C2- Centro, Joinville', NULL, 'https://www.ingresso.com/cinema/gnc-joinville-mueller?city=joinville', 'https://www.gnccinemas.com.br/', '2025-10-13 15:10:55.867065');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('25', 'GNC Nações Criciúma', 'Avenida Jorge Elias De Lucca, 677 Loja 41/42- Nossa Senhora da Salete, Criciúma', NULL, 'https://www.ingresso.com/cinema/gnc-nacoes?city=criciuma', 'https://www.gnccinemas.com.br', '2025-10-13 15:12:00.924951');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('26', 'GNC Neumarkt Shopping Blumenau ', 'R. Sete de Setembro, 1213 LOJA 214- Centro, Blumenau', NULL, 'https://www.ingresso.com/cinema/gnc-neumarkt-shopping?city=blumenau', 'https://www.gnccinemas.com.br', '2025-10-13 15:12:50.108177');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('27', 'PlayArte Praça da Moça', 'Rua Manoel da Nóbrega, 712 - Shopping Praça da Moça - Centro - Diadema - SP', NULL, 'https://www.playartecinemas.com.br/cinema/playarte-praca-da-moca', 'https://www.playartecinemas.com.br/cinema/playarte-praca-da-moca', '2025-10-06 12:29:52.852547');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('28', 'PlayArte Shopping ABC', 'Av. Pereira Barreto, 42 - Shopping ABC - Vila Gilda - Santo André - SP', NULL, 'https://www.playartecinemas.com.br/cinema/playarte-abc', 'https://www.playartecinemas.com.br/cinema/playarte-abc', '2025-10-06 12:30:27.604173');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('29', 'PlayArte Shopping Ibirapuera', 'Av. Ibirapuera, 3103 - Shopping Ibirapuera - Piso Campo Belo - Indianópolis - São Paulo - SP', NULL, 'https://www.playartecinemas.com.br/cinema/playarte-ibirapuera', 'https://www.playartecinemas.com.br/cinema/playarte-ibirapuera', '2025-10-06 12:31:17.671662');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('30', 'PlayArte Marabá', 'Av. Ipiranga, 757 - Centro - São Paulo - SP', NULL, 'https://www.playartecinemas.com.br/cinema/playarte-maraba', 'https://www.playartecinemas.com.br/cinema/playarte-maraba', '2025-10-06 12:32:07.855094');
--velox tickets
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('10', 'Cine 14 Bis', 'R. Marcelino Rivera, 007 - Irmãos Ricciaro, Guaxupé - MG, 37800-000', NULL, 'https://www.veloxtickets.com/Parceiro/P-14BIS/Ingresso/Cinema/Guaxupe', 'https://www.cine14bis.com.br/programacao/', '2025-07-09 19:00:02.360304');
--csingresso.com.br
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('11', 'Cine Premier Formosa ', 'Av. Maestro João Luiz do Espírito Santo, 200 - Formosinha, Formosa - GO, 73813-030', NULL, 'https://csingresso.com.br/home/cidade/5208004/empresa/Cinemas%20Premier%20Formosa', 'https://csingresso.com.br/home/cidade/5208004/empresa/Cinemas%20Premier%20Formosa', '2025-07-29 09:30:23.594816');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('15', 'Cine Premier Lem', 'R. Goiás, 100 - Mimoso do Oeste, Luís Eduardo Magalhães - BA', NULL, 'https://csingresso.com.br/home/cidade/2919553/empresa/Cinemas%20Premier%20LEM', 'https://csingresso.com.br/home/cidade/2919553/empresa/Cinemas%20Premier%20LEM', '2025-07-29 09:36:24.373852');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('31', 'Cine Premier Guanambi', 'Av. Gov. Nilo Coelho, 2135 - Amanbai, Guanambi - BA, 46430-000', NULL, 'https://csingresso.com.br/home/cidade/2911709/empresa/Cinemas%20Premier%20Guanambi', 'https://csingresso.com.br/home/cidade/2911709/empresa/Cinemas%20Premier%20Guanambi', '2025-07-29 09:37:19.211971');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('32', 'Cine Premier Barreiras', 'R. das Turbinas, 1562 - Barreirinhas, Barreiras - BA, 47811-003', NULL, 'https://csingresso.com.br/home/cidade/2903201/empresa/Cinemas%20Premier%20Barreiras', 'https://csingresso.com.br/home/cidade/2903201/empresa/Cinemas%20Premier%20Barreiras', '2025-07-29 09:38:08.852015');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('33', 'Formosa', 'Av. Maestro João Luiz do Espírito Santo, 200 - Formosinha, Formosa - GO, 73813-030', NULL, 'https://csingresso.com.br/home/cidade/5208004/empresa/Cinemas%20Premier%20Formosa', 'https://csingresso.com.br/home/cidade/5208004/empresa/Cinemas%20Premier%20Formosa', '2025-08-13 21:09:33.186608');
insert into "cinemas" ("id", "nome", "endereco", "telefone", "url_comprar_ingresso", "url_conferir_horarios", "created_at") values ('34', 'Cine Center', 'R. Alberto Baranjak, 505 - São Cristóvão , Sinop - MT, 78557-484', NULL, 'https://www.cinecenter.com.br/#/#filmes-em-cartaz', 'https://www.cinecenter.com.br/#/#filmes-em-cartaz', '2025-07-09 18:50:29.885791');


